(display (if (> 6 (+ 5 4)) "TRUE" "FALSE")) (newline)
(display (if (equal? 4 4) "YES" "NO")) (newline)
(display (if (= 6 (remainder 16 10)) (display "OK"))) (newline)
(define a 5)
(display (if ( >= a 5) "a is 5" "a is not 5")) (newline)
(if (= (* 5 5) 25) (begin (display "answer is ") (display "5 * 5 is 25"))) (newline)
