(define a 3)
(set! a 7)
(display a) (newline)
(set! a "HELLO")
(display a) (newline)
(set! a (+ 5 (- 10 5)))
(display a) (newline)
(set! a (if(> 10 2) 5 6))
(display a) (newline)
(set! a (if (> 2 8) "T" "F"))
(display a) (newline)
